# Ruff configuration for AI Hotel Revenue Optimizer

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I", "N", "D", "UP", "B", "C", "T", "Q"]
ignore = []

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[pep8-naming]
# Allow Streamlit's custom exception names
classmethod-decorators = ["classmethod", "validator", "root_validator"]

[isort]
known-first-party = ["app", "src", "tests"]
combine-as-imports = true

[pydocstyle]
convention = "google"

[pycodestyle]
max-doc-length = 88

[flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[per-file-ignores]
"tests/*" = ["D", "N802", "N803"]
"**/__init__.py" = ["F401"]
"app/streamlit_app.py" = ["T201"]  # Allow print statements in Streamlit app

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = 88
