llm:
  model: "mistral:7b-instruct"
  temperature: 0.7

hotel:
  name: "Mon Hôtel"
  category: "4 étoiles"
  total_rooms: 100

competitor_analysis:
  update_frequency: "daily"
  max_competitors: 5
  search_radius_km: 5